version: '2'
services:
    influxdb:
        restart: always
        image: 'influxdb:1.3-alpine'
        ports:
            - '8086:8086'
            - '8083:8083'
        volumes:
            - './conf/influxdb:/var/lib/influxdb'
        environment:
            INFLUXDB_DB: 'faucet'
            INFLUXDB_HTTP_AUTH_ENABLED: 'true'
            INFLUXDB_ADMIN_USER: 'faucet'
            INFLUXDB_ADMIN_PASSWORD: 'faucet'

#    prometheus:
#        restart: always
#        image: 'prom/prometheus:v2.0.0'
#        user: 'root'
#        ports:
#            - '9090:9090'
#        volumes:
#            - './conf/prometheus/:/prometheus'
#            - './etc/prometheus/prometheus-docker-compose.yml:/etc/prometheus/prometheus.yml'
#            - './etc/prometheus/faucet.rules.yml:/etc/prometheus/faucet.rules.yml'
#        links:
#            - faucet
#            - gauge

#    grafana:
#        restart: always
#        image: 'grafana/grafana:4.5.2'
#        ports:
#            - '3000:3000'
#        volumes:
#            - './conf/grafana:/var/lib/grafana'
#        links:
#            - influxdb
#            - prometheus

    gauge:
        restart: always
        image: 'faucet/gauge:latest'
        environment:
            GAUGE_CONFIG: '/etc/faucet/gauge.yaml'
        volumes:
            - './conf/:/var/log/faucet'
            - './conf/:/etc/faucet'
        ports:
            - '6654:6653'
            - '9303'
        links:
            - influxdb

    faucet_extended:
        restart: always
        build:
            context: ./extension/
            dockerfile: Dockerfile
        image: 'nats-adapter:faucet'
        volumes:
            - './conf/:/var/log/faucet'
            - './conf/:/etc/faucet'
        ports:
            - '6653:6653'
            - '9302'
        environment:
            FAUCET_CONFIG_STAT_RELOAD: '${FAUCET_CONFIG_STAT_RELOAD}'
            FAUCET_EVENT_SOCK: '1'
            NATS_URL: 'nats://localhost:4222'


    gnatsd:
        restart: always
        image: 'nats:latest'
        ports:
            - '4222:4222'
            - '8222:8222'
            - '6222:6222'
