server:

  requestLog:
      appenders: []
#      - type: console
#        layout:
#          type: access-json
#          timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
#          requestHeaders:
#              - User-Agent
#              - X-Request-Id

  applicationConnectors:
    - type: http
      port: 9000
#    - type: https
#      port: 8443
#      keyStorePath: keystores/seer.jks
#      keyStorePassword: seer
#      keyStoreType: JKS

  adminConnectors:
    - type: http
      port: 9001
#    - type: https
#      port: 8444
#      keyStorePath: keystores/seer.jks
#      keyStorePassword: seer
#      keyStoreType: JKS
#      trustStorePath: /path/to/file
#      trustStorePassword: changeit
#      trustStoreType: JKS

controller:
  type: floodlight
#  hostname: ${CTR_HOSTNAME:-localhost}
#  port: ${CTR_PORT:-8080}
  hostname: localhost
  port: 8080

mudControllers:
  - id: "urn:ietf:params:mud:dns"
    value: "192.168.111.1"
  - id: "urn:ietf:params:mud:ntp"
    value: "192.168.111.1"
  - id: "urn:ietf:params:mud:gateway"
    value: "192.168.111.1"

logging:
  level: ERROR
  loggers:
    com.networkseer: INFO
#    feign: DEBUG
  appenders:
    - type: console
      threshold: INFO
    - type: file
      currentLogFilename: logs/network-seer.log
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: logs/network-seer-%d{yyyy-MM-dd}-%i.log
      archivedFileCount: 10
      timeZone: UTC
      maxFileSize: 10Mb

switches:
  - "0xf4f26d229e7c"

swagger: True
